# Generated by Django 5.2.1 on 2025-05-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentrecord_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='student_id',
            field=models.CharField(max_length=255),
        ),
    ]
